### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by audreywatters** [michaelarthurcaulfield/wikity-zero#1]
I created a page called "home" (so that the "home" URL on the landing page resolves).

But it throws a "fatal error" (Screenshot below)

![home_ _notes](https://cloud.githubusercontent.com/assets/451360/17332595/2b2da600-5884-11e6-980a-278aff4e9fb1.png)

**Comment by cpjobling** [comment]
I don't have a solution but it looks like there's a library that the theme needs (markdown parser for wordpress) missing. Perhaps the installation instructions need to be updated if the library can't or shouldn't be added to the theme.

**Comment by michaelarthurcaulfield** [comment]
Unlike "cards" the "pages" don't use Markdown (just HTML) and don't need the parser, but there's a call somewhere in the chain to the parser. So I'll find it and remove it (or wrap it in a condition). It's a fairly benign error though, occurring on pages, and only then after render. I'll get it fixed, but it shouldn't hold you back from installation.

**Comment by michaelarthurcaulfield** [comment]
Closed. Fixed in latest update. On pages only footer is now replaced by generic Wikity footer and link to github.
